version: '3.5'

services:
  {{ (ds "config").DNS_PREFIX | strings.ReplaceAll "." "-" }}-{{ (ds "config").DNS_SUFFIX | strings.ReplaceAll "." "-" }}:
    image: ${DOCKER_REGISTRY}{{ (ds "config").DNS_PREFIX }}.{{ (ds "config").DNS_SUFFIX }}:${BRANCH:-develop}.${VERSION:-local}-tests
    container_name: tests
    build:
      target: tests
    environment:
      RUN_SONARQUBE: ${RUN_SONARQUBE:-true}
      SONARQUBE_URL: ${SONARQUBE_URL:-http://172.17.0.1:9000}
      SONARQUBE_LOGIN: ${SONARQUBE_LOGIN}
      SONARQUBE_PROJECT: {{ (ds "config").DNS_PREFIX }}.{{ (ds "config").DNS_SUFFIX }}
      SONARQUBE_PROJECT_VERSION: ${BRANCH:-develop}.${VERSION:-local}
    env_file: env-tests.env
